language: minimal

services:
  - docker

jobs:
  include:
    - stage: deploy
      script: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
        docker run --rm -t \
        -v $(pwd):/myvol \
        -e DOCKER_USER=${DOCKER_USERNAME} \
        -e DOCKER_PASS=${DOCKER_PASSWORD} \
        -e PUSHRM_PROVIDER=dockerhub \
        -e PUSHRM_FILE=/myvol/README.md \
        -e PUSHRM_SHORT='Docker image for Dolibarr with auto installer on first boot.' \
        -e PUSHRM_TARGET=docker.io/tuxgasy/dolibarr -e PUSHRM_DEBUG=1 \
        chko/docker-pushrm:1

    - stage: test
      if: type = pull_request
      before_install:
        - ./update.sh
      script:
        - git diff --exit-code
      after_failure:
        - echo "Run the update.sh script before pull request"

    - stage: test
      if: type = pull_request
      env:
        - DOLI_INSTALL_AUTO=0
      before_install:
        - ./update.sh
        - docker build -t tuxgasy/dolibarr:develop images/develop
        - docker run -d -p 127.0.0.1:80:80 --name dolibarr tuxgasy/dolibarr:develop
      script:
        - docker ps | grep -q dolibarr

    - stage: deploy
      if: type = push AND branch = master
      env:
        - DOCKER_BUILD=1 DOCKER_PUSH=1
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - ./update.sh
