services:
  - docker

env:
  - DOCKER_BUILD=1
  - DOLI_INSTALL_AUTO=0

before_install:
  - ./update.sh
  - docker build -t tuxgasy/dolibarr:develop images/develop
  - docker run -d -p 127.0.0.1:80:80 --name dolibarr tuxgasy/dolibarr:develop

script:
  - docker ps | grep -q dolibarr
