language: minimal

services:
  - docker

jobs:
  include:
    - stage: test
      if: type = pull_request
      before_install:
        - ./update.sh
      script:
        - git diff --exit-code
      after_failure:
        - echo "Run the update.sh script before pull request"

    - stage: test
      if: type = pull_request
      env:
        - DOLI_INSTALL_AUTO=0
      before_install:
        - DOCKER_BUILD=1 ./build.sh develop
        - docker run -d -p 127.0.0.1:80:80 --name dolibarr tuxgasy/dolibarr:develop
      script:
        - docker ps | grep -q dolibarr
