language: minimal

services:
  - docker

jobs:
  include:
    - stage: test
      if: type = pull_request
      before_install:
        - ./update.sh
      script:
        - git diff --exit-code
      after_failure:
        - echo "Run the update.sh script before pull request"

    - stage: test
      if: type = push
      env:
        - DOCKER_BUILD=1 DOLI_INSTALL_AUTO=0
      before_install:
        - ./update.sh
        - docker build -t tuxgasy/dolibarr:develop images/develop
        - docker run -d -p 127.0.0.1:80:80 --name dolibarr tuxgasy/dolibarr:develop
      script:
        - docker ps | grep -q dolibarr

    - stage: deploy
      if: type = push AND branch = master
      env:
        - DOCKER_BUILD=1 DOCKER_PUSH=1
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - ./update.sh
